### ISSUE TITLE
Support for '--profile' AWS CLI option?

### ISSUE THREAD

**Issue by gregglowrimore** [mifi/cognito-backup#10]
We have 3+ AWS accounts and thus utilize the '--profile' CLI option all the time. Can this support be added as a CLI option to your backup script?

**Comment by mifi** [comment]
You could have used AWS_PROFILE env variable. But I have now implemented this flag also. Took code from https://github.com/mifi/dynamodump/pull/4/files :)

upgrade to 2.1.0 🆕
