### ISSUE TITLE
User Groups

### ISSUE THREAD

**Issue by VagyokC4** [mifi/cognito-backup#11]
Thanks for the great tool.  We backed up from one region and restored to another, however, we were missing user's groups.  Any plans on including the user groups in the future?

**Comment by mifi** [comment]
I'm open to including this if there's no good reason not to. But I don't have time to implement/test now.

**Comment by toelke** [comment]
I implemented this, see PR #19

**Comment by s10z** [comment]
Hey @mifi this pull request is quite old now and your tool is quite in use I guess. Any time to verify and allow the pull request of @toelke? Having user groups extracted, too would be highly beneficial.
