### ISSUE TITLE
Restore is not working

### ISSUE THREAD

**Issue by djakielski** [mifi/cognito-backup#15]
I execute `cognito-backup restore-users eu-central-xxxxx Abcd.1234 --region eu-central-1 --file userpool-dev.json ` and get no result with error code 0. But in the AWS Userpool, there are no users.

**Comment by mifi** [comment]
Is it possible to share the file, or a minimum reproducable case that contains no sensitive data?

**Comment by mifi** [comment]
This is strange. I tried to run on my test AWS:
```
cognito-backup restore-users eu-west-1_GFxlursRr Abcd.1234 --region eu-west-1 --file ~/Downloads/sample.txt
```
 and it works (after changing the emails to valid emails)

**Comment by mifi** [comment]
any way to reproduce this problem?

**Comment by mifi** [comment]
I have now done some rewrite that hopefully will prevent this
