### ISSUE TITLE
Cli.js File error

### ISSUE THREAD

**Issue by shivm-04** [mifi/cognito-backup#29]
I am getting this error while backing up groups
**Command ;- cognito-backup backup-groups eu-west-1_12345 --region us-east-1 --file eu-west-1_12345.json

**error :-
    file:///usr/local/lib/node_modules/cognito-backup/cli.js:218
    debug('Restored user', response?.User?.Username);
                                    ^

SyntaxError: Unexpected token '.'
    at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)
    at async link (internal/modules/esm/module_job.js:42:21)

**Comment by mifi** [comment]
Maybe too old node.js version?

**Comment by shivm-04** [comment]
Node.js  12 version is running
v12.22.9

is this version comfortable for congnito  backup ?

**Comment by mifi** [comment]
Use 16 or newer

**Comment by shivm-04** [comment]
Thanks mifi Now its working
You Saved my lot of time
