### ISSUE TITLE
More detailed restore logging

### ISSUE THREAD

**Issue by jakub-qg** [mifi/cognito-backup#32]
Hello,

Thanks for creating such a useful tool!

I have a usecase I'd like to implement however I want to start a discussion before I make a pull request.

I need to cross-reference old and new user identities (`sub`). I'd like the tool to output something like:
```
User created oldSub":"xxx" newSub: "yyy"
```
for each restored user.

Now, I understand other people may want different output formats, fields, etc. hence I'd like to introduce templating (most likely with `handlebars`).

The CLI would work like so:
```
cognito-backup restore-users pool_id "Abcd.1234" --file users.json --out-template "{{source.Attributes.sub}} {{response.Attributes.sub}}"
```

**Comment by mifi** [comment]
Hi. Il not sure how the out-template argument would work but maybe we can just add a console log? Enabled by a verbose flag
