### ISSUE TITLE
TooManyRequestsException: Rate exceeded

### ISSUE THREAD

**Issue by ronnieguha** [mifi/cognito-backup#6]
Since I am trying to import about 500 users, I end up hitting this issue. Any chance that a backoff can be implemented, or any way to batch functions? What I end up with is about 80 users created and unless I delete all users, I cannot re-run this..

**Comment by mifi** [comment]
I have published a new version 2.0.0 now that will throttle requests to 5 per second, which should be within the [limits](https://docs.aws.amazon.com/cognito/latest/developerguide/limits.html).

Ps as of 2.0.0 requires at least node 8. Reopen if still an issue
