### ISSUE TITLE
Error happens when backup

### ISSUE THREAD

**Issue by szkkeny** [mifi/cognito-backup#9]
When I run below command,
```
cognito-backup backup-users [pool_id] --region [resion]
```
the backup fails with below message. 
```
Error: connect ETIMEDOUT [IP:port]
at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1163:14)
```
Are there any settings or options I should do?

Thanks,

**Comment by mifi** [comment]
Looks like something is blocking access to the amazon servers. can you try a different computer or internet connection?

**Comment by szkkeny** [comment]
Thanks!
I will try it.

**Comment by mifi** [comment]
reopen if still an issue
